Update main.yml
open-io/ansible-role-openio-oioswift pull request #10
Opened 2018-11-05 12:41 UTC by GeoffreyTien

Config for container_hierarchy plugin

2018-11-05 14:51 UTC, vincent-legoll commented on defaults/main.yml
> +  sentinel_hosts:
ca serait pas mieux dans le role redis, tout ça ?

2018-11-07 15:15 UTC, cdelgehier requested changes

2018-11-07 15:15 UTC, cdelgehier commented on defaults/main.yml
> +  sentinel_name: "{{ openio_oioswift_sds_proxy_namespace }}-master-1 "
Use `openio_oioswift_namespace` instead of `openio_oioswift_sds_proxy_namespace`

2018-11-07 15:15 UTC, cdelgehier commented on defaults/main.yml
> +    "{{ groups['openio_redis_cluster'] \
Replace this jinja by a default value like `192.168.1.1:6012,192.168.1.2:6012,192.168.1.3:6012`
Playbook will map extract the needed value.

2018-11-07 15:15 UTC, cdelgehier commented on defaults/main.yml
> +#  create_dir_placeholders: true
why leave that there?

2018-11-14 21:23 UTC, closed without merging