[19.04] Keep each cache entry (object metadata and location) for up to 1 hour
open-io/ansible-role-openio-oioswift pull request #102
Opened 2021-03-23 13:56 UTC by AymericDu

2021-03-24 09:46 UTC, fatpat approved these changes

2021-03-24 09:58 UTC, vincent-legoll approved these changes

2021-03-29 15:12 UTC, cdelgehier requested changes
19.04 and 20.04 are merged in skeleton
https://github.com/open-io/customer-skeleton/blob/19.04/deployment/sds/roles/oioswift/defaults/main.yml#L84

2021-03-29 21:28 UTC, AymericDu commented
https://github.com/open-io/customer-skeleton/pull/519

2021-03-29 21:28 UTC, closed without merging