[20.04] Keep each cache entry (object metadata and location) for up to 1 hour
open-io/ansible-role-openio-oioswift pull request #104
Opened 2021-03-23 13:57 UTC by AymericDu

2021-03-24 09:47 UTC, fatpat approved these changes

2021-03-24 09:59 UTC, vincent-legoll approved these changes

2021-03-29 15:14 UTC, cdelgehier requested changes

2021-03-29 15:14 UTC, cdelgehier commented on defaults/main.yml
> -  oio_cache_ttl: 0
https://github.com/open-io/customer-skeleton/blob/20.04/deployment/sds/collections/ansible_collections/openio/community/roles/oioswift/defaults/main.yml#L106

Can you PR this line ?

2021-03-29 21:28 UTC, AymericDu commented
https://github.com/open-io/customer-skeleton/pull/520

2021-03-29 21:28 UTC, closed without merging