CHANGE(oioswift): Split memcached group
open-io/ansible-role-openio-oioswift pull request #51
Opened 2019-09-26 09:16 UTC by fatpat

##### SUMMARY

Currently, memcached is deployed on groups `oioswift` and `keystone`
without the possibility to deploy them elsewhere

Like the redis group, the memcached group can now be split into two
groups:

    memcached-keystone for keystone auth cache
    memcached-swift for swift cache

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

2019-09-27 13:07 UTC, cdelgehier commented on README.md
> +| `openio_oioswift_memcached_keystone_inventory_groupname` | `"memcached-keystone" | "memcached" | "oioswift"` | memcached groupname for keystone cache in your inventory |
missing `

2019-09-27 13:07 UTC, cdelgehier commented on README.md
> +| `openio_oioswift_memcached_swift_inventory_groupname` | `"memcached-swift" | "memcached" | "oioswift"` | memcached groupname for swift cache in your inventory |
missing `

2019-09-27 16:48 UTC, fatpat commented on README.md
> +| `openio_oioswift_memcached_keystone_inventory_groupname` | `"memcached-keystone" | "memcached" | "oioswift"` | memcached groupname for keystone cache in your inventory |
fixed

2019-09-27 16:48 UTC, fatpat commented on README.md
> +| `openio_oioswift_memcached_swift_inventory_groupname` | `"memcached-swift" | "memcached" | "oioswift"` | memcached groupname for swift cache in your inventory |
fixed

2019-10-08 08:51 UTC, cdelgehier requested changes
Can you avoid the use of dashes in group names ?

2019-11-18 16:42 UTC, fatpat commented
> Can you avoid the use of dashes in group names ?

fixed !

2019-11-18 17:16 UTC, merged